version: '3.1'

services:
  tgbot-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dev_tgbot_db'
      MYSQL_USER: 'dev_tgbot_db_user'
      MYSQL_PASSWORD: 'dev_tgbot_db_password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3366:3306'
    expose:
      - '3366'