version: '3.1'

services:
  tgbot:
    depends_on:
      - tgbot-db
    build:
      context: .
    environment:
      - BOT_NAME=${BOT_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
    restart: always

  tgbot-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'tgbot_db'
      MYSQL_USER: ${BOT_DB_USERNAME}
      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3366:3306'
    expose:
      - '3366'

